### ISSUE TITLE
Icons are slightly offset on mobile

### ISSUE THREAD

**Issue by RoiEXLab** [xxhomey19/github-file-icon#33]
Not a big deal, but I just noticed this:
![grafik](https://user-images.githubusercontent.com/8350879/37788348-8002f4e2-2e01-11e8-9496-ed1f62462f60.png)
Tested on Firefox for Android.

**Comment by xxhomey19** [comment]
This is definitely a bug 😕

**Comment by arnellebalane** [comment]
The misalignment of the file icons on GitHub is caused by the removal of the `octicon` class on the icon element, introduced in this commit: https://github.com/xxhomey19/github-file-icon/commit/8889ab564c579526a5ddb095c6d9e81ccddc70b7?diff=split#diff-58abb088be4b02338aacb69a0580ab7f

The `octicon` class absolutely-positions the icon element to the left.

**Comment by xxhomey19** [comment]
Hey @RoiEXLab I have uploaded a new version on Firefox. Should fix this issue.

**Comment by arnellebalane** [comment]
Can confirm that `0.4.2` has fixed the issue on Firefox for Android :100:

**Comment by xxhomey19** [comment]
Close due to no response, and it has been fixed.

**Comment by RoiEXLab** [comment]
@xxhomey19 Sorry for not responding 😅
I probably missed your comment back then.
Thanks for fixing this 👍

**Comment by xxhomey19** [comment]
It's okay. 👍
