### ISSUE TITLE
Travis image update

### ISSUE THREAD

**Issue by aashutoshrathi** [xxhomey19/github-file-icon#56]
I think we should use this image for Travis: https://github.com/PKief/vscode-material-icon-theme/blob/master/icons/travis.svg

**Comment by xxhomey19** [comment]
Hey @aashutoshrathi 
sorry I can't really really change what image should be shown at this moment, because this extension uses [websemantics/file-icons-js](https://github.com/websemantics/file-icons-js) to determine the icon. However, the author seems not to maintain it for a while.
This kind of issues has been reported a few times (like #47). I think the best way to solve these issues is to fork `file-icons-js` and keep updating it. I probably will do it one day, but until that happens, nothing I can help sorry 😕
